site_name: EZInput

# Documentation and theme
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'magenta'
    accent: 'light blue'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

markdown_extensions:
  - admonition
  - codehilite

pages:
  - Getting started: 'index.md'
  - Bindings: 'bindings.md'
  - Controller profiles: 'controller-profiles.md'
  - The test scene: 'the-test-scene.md'
  - Code reference: 'code-reference.md'
  - The EzInput prefab: 'the-ezinput-prefab.md'